accounts/urls.py
# coding: utf-8
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', csrf_exempt(views.login), name='login'),
    url(r'^register$', csrf_exempt(views.register), name='register'),
    url(r'^password_modify$', csrf_exempt(views.password_modify), name='password_modify'),
    url(r'^email_confirm$', csrf_exempt(views.email_confirm), name='email_confirm'),
]

case/urls.py
# coding: utf-8
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import views

urlpatterns = [
    url(r'^list$', csrf_exempt(views.list), name='list'),
    url(r'^choosecase$', csrf_exempt(views.choosecase), name='choosecase'),
    url(r'^choosecareer$', csrf_exempt(views.choosecareer), name='choosecareer'),
    url(r'^study_02/(?P<name>[\u4e00-\u9fa5]{0,})$', csrf_exempt(views.study_02), name='study_02'),
    url(r'^study_01/(?P<name>[\u4e00-\u9fa5]{0,})$', csrf_exempt(views.study_01), name='study_01'),
]

phls/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    url(r'^test/', include('testmode.urls')),
    url(r'^guide/', include('guide.urls')),
    url(r'^case/', include('case.urls')),
]

accounts/models.py
# coding: utf-8
from django.db import models
import random

# Create your models here.


class Accounts(models.Model):
	name = models.CharField(max_length=30, verbose_name='用户名')
	password = models.CharField(max_length=20, verbose_name='密码')
	email = models.EmailField(max_length=100, primary_key=True, verbose_name='邮箱')
	role = models.BooleanField(default=False, verbose_name='是否为管理员') # yes--manage role
	create_date = models.DateTimeField(auto_now_add=True, verbose_name='创建日期') # 创建日期
	modified_date = models.DateTimeField(auto_now_add=True, verbose_name='修改日期') # 修改日期
	confirm_code = models.CharField(blank=True, max_length=6, verbose_name='验证码')
	is_active = models.BooleanField(default=False, verbose_name='是否有效')

	class Meta:
		verbose_name = '用户账号'
		verbose_name_plural = '用户账户'

	def __str__(self):
		return self.name

	def set_confirm_code(self):
		confirm_code = ''
		code_list = []
		for i in range(6):
			statu = random.randint(1, 3)
			if statu == 1:
				a = random.randint(65, 90)
				random_uppercase = chr(a)
				code_list.append(random_uppercase)
			elif statu == 2:
				b = random.randint(97, 122)
				random_lowercase = chr(b)
				code_list.append(random_lowercase)
			elif statu == 3:
				random_num = random.randint(0, 9)
				code_list.append(str(random_num))

		confirm_code = "".join(code_list)
		self.confirm_code = confirm_code.lower()
		self.save()
		return self.confirm_code

accounts/views.py
# coding: utf-8
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from .models import Accounts
from django.core.mail import send_mail
from smtplib import SMTPException

# Create your views here.

# 数据库管理请求 路由：'/admin'
# def


# 处理登录界面请求 路由：'/'
def login(request):
    request.encoding = 'utf-8'
    context = {}
    error_msg = ''
    if request.method == "POST":
        email = request.POST['account_email']
        psd = request.POST['account_password']
        try:
            account_id = Accounts.objects.get(email=email)
            if account_id and account_id.password == psd:
                # 跳转到系统主页
                context['account'] = account_id
                # request.set_cookie('email', email, 3600)
                return render(request, 'guide/guide.html', context=context)
            else:
                # 用户密码不匹配
                error_msg = '用户邮箱或密码错误！'
        except Accounts.DoesNotExist:
            error_msg = '用户不存在！请注册后重试！'

    context['error_msg'] = error_msg
    return render(request, 'accounts/login.html', context=context)


# 处理用户注册请求  路由：'/'
def register(request):
    context = {}
    error_msg = ''
    if request.method == 'POST':
        user_name = request.POST['account_name']
        email = request.POST['account_email']
        psd = request.POST['account_password']
        psd2 = request.POST['account_password2']
        try:
            Accounts.objects.get(email=email)
            # 如果没有查找到数据，会报 DoesNotExist 错误
            error_msg = '该邮箱已被使用！请重新输入！'
        except Accounts.DoesNotExist:
            # 判断两次密码是否一致
            if psd == psd2:
                Accounts(name=user_name, email=email, password=psd).save()
                return render(request, 'accounts/login.html', context=context)
            else:
                error_msg = '两次输入的密码不匹配！'

    context['error_msg'] = error_msg
    return render(request, 'accounts/register.html', context=context)


# 找回密码前邮箱确认请求处理   路由：'/'
def email_confirm(request):
    context = {}
    error_msg = ''
    context['account_email'] = ''
    if request.method == 'POST':
        email = request.POST['account_email']
        context['account_email'] = email
        account_confirm_code = request.POST['account_confirm_code'].lower()

        try:
            account_id = Accounts.objects.get(email=email)
            context['account_email'] = account_id.email
            confirm_code = account_id.confirm_code
            if not confirm_code:
                confirm_code = account_id.set_confirm_code()
                subject = '找回密码 | 验证邮件'
                message = '\n\r验证码如下：\n\r' + confirm_code + '\n\r'
                try:
                    send_mail(subject, message, '3071729230@qq.com', ['lichenglin2014.com@outlook.com'])
                except SMTPException:
                    return
            condition = (account_confirm_code == confirm_code)
            if not account_confirm_code or not condition:
                error_msg = '请填写正确的验证码！'
            else:
                account_id.confirm_code = ''
                account_id.save()
                return render(request, 'accounts/passwordmodify.html', context=context)
        except Accounts.DoesNotExist:
            error_msg = '该邮箱未注册！请确认后重试！'

    context['error_msg'] = error_msg
    return render(request, 'accounts/emailconfirm.html', context=context)


# 密码修改请求处理  路由：'/password_modify'
def password_modify(request):
    context = {}
    error_msg = ''
    if request.method == 'POST':
        email = request.POST['account_email']
        psd = request.POST['account_password']
        psd2 = request.POST['account_password2']
        account_id = Accounts.objects.get(email=email)
        # 判断两次密码是否一致
        if psd == psd2:
            account_id.password = psd
            account_id.save()
            context['account'] = account_id
            return render(request, 'accounts/login.html', context=context)
        else:
            error_msg = '两次输入的密码不一致！请重新输入！'

    context['error_msg'] = error_msg
    return render(request, 'accounts/passwordmodify.html', context=context)

templates/accounts/emailconfirm.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>找回密码 | 虚拟宠物医院学习系统</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FreeHTML5.co" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	

  

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<!--<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>-->
	
	<link rel="stylesheet" href="{% static 'accounts/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'accounts/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'accounts/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'accounts/js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body class="style-2">

		<div class="container">
				<div class="col-md-4">
					

					<!-- Start Sign In Form -->
					<form action="./email_confirm" method="post" class="fh5co-form animate-box" data-animate-effect="fadeInLeft">
						<h2>Forgot Password</h2>
						<div class="form-group">
							<div class="alert alert-success" role="alert">{{error_msg}}</div>
						</div>
						<div class="form-group">
							<label for="id_email" class="sr-only">Email</label>
							<input type="email" class="form-control" name="account_email" id="id_email" placeholder="Email" autocomplete="off">
						</div>
						<div class="form-group">
							<label for="id_confirm_code" class="sr-only">Confirm Code</label>
							<input type="text" class="form-control" name="account_confirm_code" id="id_confirm_code" placeholder="Confirm Code" autocomplete="off">
						</div>
						<!--<div class="form-group">-->
							<!--<p><a href="index2.html">Sign In</a> or <a href="sign-up2.html">Sign Up</a></p>-->
						<!--</div>-->
						<div class="form-group">
							<input type="submit" value="Send Email" class="btn btn-primary">
						</div>
					</form>
					<!-- END Sign In Form -->


				</div>
			</div>
			<div class="row" style="padding-top: 60px; clear: both;">
			</div>
		</div>
	
	<!-- jQuery -->
	<script src="{% static 'accounts/js/jquery.min.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'accounts/js/bootstrap.min.js' %}"></script>
	<!-- Placeholder -->
	<script src="{% static 'accounts/js/jquery.placeholder.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'accounts/js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'accounts/js/main.js' %}"></script>

	</body>
</html>

templates/accounts/login.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>登录 | 虚拟医院学习系统</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FreeHTML5.co" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
	
	<link rel="stylesheet" href="{% static 'accounts/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'accounts/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">


	<!-- Modernizr JS -->
	<script src="{% static 'accounts/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'accounts/js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body class="style-2" onload="checkCookie()">

		<div class="container">
				<div class="col-md-4">
					

					<!-- Start Sign In Form -->
					<form action="./" method="post" id="login-form" class="fh5co-form animate-box" data-animate-effect="fadeInLeft">
						<h2>Sign In</h2>
						<div class="form-group">
							<label for="id_account_email" class="sr-only">User Email:</label>
							<input type="email" class="form-control" name="account_email" id="id_account_email" placeholder="User email" autocomplete="off">
						</div>
						<div class="form-group">
							<label for="id_account_password" class="sr-only">Password:</label>
							<input type="password" class="form-control" name="account_password" id="id_account_password" placeholder="Password" autocomplete="off">
						</div>
						<div class="form-group">
							<label for="remember"><input type="checkbox" id="remember"> Remember Me</label>
						</div>
						<div class="form-group">
							<span style="color:red;">&nbsp;{{ error_msg }}</span>
						</div>
						<div class="form-group">
							<p>Not registered? <a href="./register">Sign Up</a> | <a href="./email_confirm">Forgot Password?</a></p>
						</div>
						<div class="form-group">
							<input type="submit" value="Sign In" class="btn btn-primary">
						</div>
					</form>
					<!-- END Sign In Form -->

				</div>
			</div>
			<div class="row" style="padding-top: 60px; clear: both;">
			</div>
		</div>
	
	<!-- jQuery -->
	<script src="{% static 'accounts/js/jquery.min.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'accounts/js/bootstrap.min.js' %}"></script>
	<!-- Placeholder -->
	<script src="{% static 'accounts/js/jquery.placeholder.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'accounts/js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'accounts/js/main.js' %}"></script>

	</body>
</html>

templates/accounts/passwordmodify.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<html lang="en">
<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>找回密码 | 虚拟医院学习系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FreeHTML5.co" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />


  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<!--<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>-->

	<link rel="stylesheet" href="{% static 'accounts/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'accounts/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'accounts/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'accounts/js/respond.min.js' %}"></script>
	<![endif]-->
</head>

<body class="style-2">
<!-- Container -->
    <div class="container">
        <div class="col-md-4">
            <form action="./password_modify" method="post" class="fh5co-form animate-box" data-animate-effect="fadeInLeft" id="password-modify-form">
                <h2>Password Modify</h2>
                <input type="hidden" name="csrfmiddlewaretoken" value="G86dINhLAc0XQN0tbT0BCMNViwz2ds3tJrlcTC2VVukZe175Eblm7UDrBysbOnQv">
                <div class="form-group">
                    <label class="sr-only" for="id_account_email">用户邮箱:</label>
                    <input type="email" class="form-control" name="account_email" value="{{ account_email }}" readonly="1" id="id_account_email">
                </div>
                <div class="form-group">
                    <label class="sr-only" for="id_account_password">密码:</label>
                    <input type="password" class="form-control" name="account_password" autofocus="" required="" id="id_account_password" placeholder="Password">
                </div>
                <div class="form-group">
                    <label class="sr-only" for="id_account_password2">再次输入:</label>
                    <input type="password" class="form-control" name="account_password2" required="" id="id_account_password2" placeholder="ReInput Password">
                </div>
                <div class="form-group">
                    <span style="color:red;">&nbsp;{{ error_msg }}</span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Confirm" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
    <div class="row" style="padding-top: 60px; clear: both;"></div>

    <!-- jQuery -->
	<script src="{% static 'accounts/js/jquery.min.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'accounts/js/bootstrap.min.js' %}"></script>
	<!-- Placeholder -->
	<script src="{% static 'accounts/js/jquery.placeholder.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'accounts/js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'accounts/js/main.js' %}"></script>

</body>
</html>

templates/accounts/register.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>注册 | 虚拟医院学习系统</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FreeHTML5.co" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<!--<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>-->
	
	<link rel="stylesheet" href="{% static 'accounts/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'accounts/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'accounts/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'accounts/js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body class="style-2">

		<div class="container">
			<div class="col-md-4">
				<!-- Start Sign In Form -->
				<form action="./register" method="post" class="fh5co-form animate-box" data-animate-effect="fadeInLeft">
					<h2>Sign Up</h2>
					<!--<div class="form-group">-->
						<!--<div class="alert alert-success" role="alert">Your info has been saved.</div>-->
					<!--</div>-->
					<div class="form-group">
						<label for="name" class="sr-only">Name</label>
						<input type="text" class="form-control" name="account_name" autofocus="" id="name" placeholder="Name" autocomplete="off">
					</div>
					<div class="form-group">
						<label for="email" class="sr-only">Email</label>
						<input type="email" class="form-control" name="account_email" id="email" placeholder="Email" autocomplete="off">
					</div>
					<div class="form-group">
						<label for="password" class="sr-only">Password</label>
						<input type="password" class="form-control" name="account_password" id="password" placeholder="Password" autocomplete="off">
					</div>
					<div class="form-group">
						<label for="re-password" class="sr-only">Re-type Password</label>
						<input type="password" class="form-control" name="account_password2" id="re-password" placeholder="Re-type Password" autocomplete="off">
					</div>
					<div class="form-group">
						<label for="remember"><input type="checkbox" id="remember"> Remember Me</label>
					</div>
					<div class="form-row">
						<span style="color:red;">&nbsp;{{ error_msg }}</span>
					</div>
					<div class="form-group">
						<p>Already registered? <a href="./">Sign In</a></p>
					</div>
					<div class="form-group">
						<input type="submit" value="Sign Up" class="btn btn-primary">
					</div>
				</form>
				<!-- END Sign In Form -->
			</div>
		</div>
		<div class="row" style="padding-top: 60px; clear: both;"></div>

	<!-- jQuery -->
	<script src="{% static 'accounts/js/jquery.min.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'accounts/js/bootstrap.min.js' %}"></script>
	<!-- Placeholder -->
	<script src="{% static 'accounts/js/jquery.placeholder.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'accounts/js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'accounts/js/main.js' %}"></script>

	</body>
</html>